version: '3.8'
services:
  db:
    image: 'postgres:15-alpine'
    container_name: db_postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d